cmsplugin_schedule/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

from .views import EventListView

urlpatterns = patterns('',
    url(r'^get-calendar-events/(?P<calendar_slug>[\.\w-]+)/$',
       EventListView.as_view(),
       name='get-calendar-events'),
)

cmsplugin_schedule/models.py
from cms.models.pluginmodel import CMSPlugin

from django.db import models
from schedule.models.calendars import Calendar
from schedule.models.events import Occurrence
from django.contrib.auth.models import Group
from django.utils.translation import ugettext_lazy as _


class CalendarPlugin(CMSPlugin):
    calendar = models.ForeignKey(Calendar)
    

class LastEventsPlugin(CMSPlugin):
    calendar = models.ForeignKey(Calendar)
    nb_event = models.PositiveSmallIntegerField(default=5, verbose_name=_("Nb events"))
    event_type = models.ForeignKey(Group, null=True, blank=True,
                                   verbose_name=_("Group"),
                                   help_text=_("To dissociate event type"))


class EventsByPeriodPlugin(CMSPlugin):
    calendar = models.ForeignKey(Calendar)
    period = models.CharField(max_length=1, 
                              verbose_name=_("Period"),
                              default='W',
                              choices=(('D', _('Today')),
                                       ('W', _('This week')),
                                       ('M', _('This month'))))
    event_type = models.ForeignKey(Group, null=True, blank=True,
                               verbose_name=_("Group"),
                               help_text=_("To dissociate event type"))
    

@property
def is_past_due(self):
    from datetime import date
    if date.today() > self.end.date():
        return True
    return False

setattr(Occurrence, "is_past_due", is_past_due)

cmsplugin_schedule/views.py
'''
Created on 22 janv. 2014

@author: alban
'''
from django.views.generic.base import View
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404

from schedule.models import Calendar
from datetime import datetime
import json
from django.utils.timezone import utc

class EventListView(View):

    def get(self, request, calendar_slug, **kwargs):
        calendar = get_object_or_404(Calendar, slug=calendar_slug)
        start = datetime.fromtimestamp(int(request.GET.get('start')), tz=utc)
        end = datetime.fromtimestamp(int(request.GET.get('end')), tz=utc)
        occurrences = []
        for event in calendar.event_set.all():
            
            for occurrence in event.get_occurrences(start, end):
                occurrences.append({
                    'title' : occurrence.title,
                    'start' : occurrence.start.strftime('%Y-%m-%d %H:%M:%S'),
                    'end' : occurrence.end.strftime('%Y-%m-%d %H:%M:%S')
                })
        
        return HttpResponse(json.dumps(occurrences))

cmsplugin_schedule/templates/cmsplugin_schedule/event_list.html
<h1>{{instance.get_period_display}}</h1>
<ul>
	{% for event in events %}
		{# https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date #}
		{# https://docs.djangoproject.com/en/dev/ref/templates/builtins/#time #}
		<li {% if event.is_past_due %}class="old-event"{% endif %}>
		{% if instance.period == 'D' %}
			{{event.title}} - {{event.start|date:"l d F Y"|capfirst}}, {{event.start|date:"G\hi"}}-{{event.end|date:"G\hi"}}
        	<div class="desc">{{event.description}}</div>
        {% elif instance.period == 'W' %}
            {{event.title}} - {{event.start|date:"l d F Y"|capfirst}}, {{event.start|date:"G\hi"}}-{{event.end|date:"G\hi"}}
            <div class="desc">{{event.description}}</div>
		{% else %}
            {{event.title}} - {{event.start|date:"l d F Y"|capfirst}}, {{event.start|date:"G\hi"}}-{{event.end|date:"G\hi"}}
            <div class="desc">{{event.description}}</div>
		{% endif %}
		</li>
	{% endfor %}
</ul>

cmsplugin_schedule/templates/cmsplugin_schedule/schedule.html
{%load sekizai_tags %}

{% addtoblock "css" %}
<link href="{{ STATIC_URL }}css/fullcalendar.css" media="all" rel="stylesheet" type="text/css" />
{% endaddtoblock %}

{% addtoblock "js" %}
<script type="text/javascript" src="{{ STATIC_URL }}js/fullcalendar.min.js"></script>

<script>
$(document).ready(function() {

    $('#calendar').fullCalendar({
        monthNames:['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
		monthNamesShort:['janv.','févr.','mars','avr.','mai','juin','juil.','août','sept.','oct.','nov.','déc.'],
		dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
		dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
		titleFormat: {
		    month: 'MMMM yyyy',
		    week: "d[ MMMM][ yyyy]{ - d MMMM yyyy}",
		day: 'dddd d MMMM yyyy'
		},
		columnFormat: {
		    month: 'ddd',
		week: 'ddd d',
		day: ''
		},
		axisFormat: 'H:mm', 
		timeFormat: {
		    '': 'H:mm', 
		agenda: 'H:mm{ - H:mm}'
		},
		firstDay:1,
		buttonText: {
		    today: 'aujourd\'hui',
		    day: 'jour',
		    week:'semaine',
		    month:'mois'
		}, 
		header: {
		    left: 'prev,next today',
			center: 'title',
			right: ''
		},
		events: "{% url 'get-calendar-events' instance.calendar.slug %}",
    });

});
</script>
{% endaddtoblock %}     


<div id="calendar"></div>